#!/usr/bin/env bash

set -eu
set -o pipefail

ARGS=('')
for a in "$@"; do
  ARGS=(${ARGS[@]} "$a")
done

install_homebrew() {
  command -v 'brew' > /dev/null 2>&1 && return

  echo 'Installing homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
  echo 'done'
}

install_ansible() {
  command -v 'ansible' > /dev/null 2>&1 && return

  echo 'Installing ansible...'
  brew install ansible
  echo 'done'
}

run_provisioning() {
  provisioning/play.sh ${ARGS[@]}
}

main() {
  install_homebrew
  install_ansible
  run_provisioning
}

main
