#!/usr/bin/env bash

set -eu
set -o pipefail

: ${NAPSAC_PATH:="$HOME/napsac"}

ARGS=('')
for a in "$@"; do
  ARGS=(${ARGS[@]} "$a")
done

clone_napsac() {
  echo 'Cloning repo...'
  git clone git@github.com:ngtk/napsac.git $NAPSAC_PATH
  echo 'done'
}

install_homebrew() {
  command -v 'brew' > /dev/null 2>&1 && return

  echo 'Installing homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
  echo 'done'
}

install_ansible() {
  command -v 'ansible' > /dev/null 2>&1 && return

  echo 'Installing ansible...'
  brew install ansible
  echo 'done'
}

run_provisioning() {
  provisioning/play.sh ${ARGS[@]}
}

main() {
  clone_napsac
  install_homebrew
  install_ansible
  run_provisioning
}

main
