- name: install zsh
  homebrew:
    name:  zsh
    state: present

- name: search zsh bin path
  command: |
    which zsh
  register: which_zsh
  ignore_errors: yes

- debug:
    msg: '{{ which_zsh.stdout }}'

- name: add zsh to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: '{{ which_zsh.stdout }}'
  become: yes

- name: change login shell to zsh
  command: |
    chpass -s '{{ which_zsh.stdout }}'
  register: chpass_result
  until: chpass_result.rc == 0
  retries: 3
  when: |
    lookup("env", "SHELL") != which_zsh.stdout

- name: install zplug
  homebrew:
    name: zplug
    state: present

- name: Clone dircolors solarized config file
  git:
    repo: https://github.com/seebi/dircolors-solarized.git
    dest: '{{ home_path }}/.dircolors-solarized'
    accept_hostkey: yes

- name: Link dircolors
  file:
    src: '{{ home_path }}/.dircolors-solarized/dircolors.ansi-dark'
    dest: '{{ home_path }}/.dircolors'
    state: link
