- name: install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v0.18.0/minikube-darwin-amd64
    dest: /usr/local/bin/minikube
    mode: 744
  when: "ansible_os_family == 'Darwin'"
